[package]
name = "zero-scale-proxy"
version = "0.1.0"
authors = ["Markus Reiter <me@reitermark.us>"]
edition = "2018"

[dependencies]
futures = "0.3.15"
k8s-openapi = { version = "0.11.0", features = ["v1_20"] }
kube = "0.55.0"
tokio = { version = "1.3.0", features = ["io-std", "io-util", "macros", "net", "rt-multi-thread", "sync"] }
tokio-stream = { version = "0.1.6", features = ["net"] }
