on: [pull_request, push]

name: CI

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azohra/shell-linter@v0.4.0
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: |
          docker buildx create --name mybuilder
          docker buildx use mybuilder
          docker buildx build --platform linux/arm64 -t '${{ github.actor }}/zero-scale-proxy' .
          docker buildx build --platform linux/amd64 --load -t '${{ github.actor }}/zero-scale-proxy' .
      # - name: Run Docker image
      #   run: |
      #     docker run \
      #       -e PORT='25565' \
      #       -e TARGET_NAME='minecraft' \
      #       -e TARGET_NAMESPACE='default' \
      #       '${{ github.actor }}/zero-scale-proxy' -- 'true'
      - name: Log into Docker Hub
        run: echo '${{ secrets.DOCKER_TOKEN }}' | docker login -u ${{ github.actor }} --password-stdin
      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 --push -t '${{ github.actor }}/zero-scale-proxy' .
